"""added enum

Revision ID: ee01e837a2c4
Revises: d754e1b65a72
Create Date: 2024-06-28 09:00:20.127326

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "ee01e837a2c4"
down_revision: Union[str, None] = "d754e1b65a72"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pet",
        sa.Column(
            "gender", sa.Enum("male", "female", name="petgenderenum"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pet", "gender")
    # ### end Alembic commands ###
