"""added enum

Revision ID: c4edfd2cde9d
Revises: 2950bb855314
Create Date: 2024-06-27 16:03:21.698637

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "c4edfd2cde9d"
down_revision: Union[str, None] = "2950bb855314"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pet",
        sa.Column(
            "gender", sa.Enum("male", "female", name="petgenderenum"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pet", "gender")
    # ### end Alembic commands ###
